### ISSUE TITLE
The key {...} was not found in the key ring

### ISSUE THREAD

**Issue by JimmyAtSchotte** [JimmyAtSchotte/Tradgardsgolf#1]
Error message:
Unhandled exception rendering component: The key {ca1082ed-251d-4f42-b901-ce2134f00338} was not found in the key ring.
System.Security.Cryptography.CryptographicException: The key {ca1082ed-251d-4f42-b901-ce2134f00338} was not found in the key ring.
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
at Microsoft.AspNetCore.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[T](String purpose, String key)

Occours:
When a new docker spins up and user still has a tab open. Goes away if user complete closes all tabs of the app.

**Comment by JimmyAtSchotte** [comment]
According to the docs: [https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1](url)

> When hosting in a Docker container, keys should be maintained in either:
> A folder that's a Docker volume that persists beyond the container's lifetime, such as a shared volume or a host-mounted volume.
> An external provider, such as Azure Key Vault or Redis.

**Comment by JimmyAtSchotte** [comment]
Switched to use LocalStorage from Blazored.LocalStorage instead and that fixed the issue.
